#!/usr/bin/env bash

python "./ElectoralCollegeMakerByYear.py" -o -y "1964" && inkscape --without-gui "ElectoralCollege1964.svg" --export-png="ElectoralCollege1964.png"
python "./ElectoralCollegeMakerByYear.py" -o -y "1968" && inkscape --without-gui "ElectoralCollege1968.svg" --export-png="ElectoralCollege1968.png"
python "./ElectoralCollegeMakerByYear.py" -o -y "1972" && inkscape --without-gui "ElectoralCollege1972.svg" --export-png="ElectoralCollege1972.png"
python "./ElectoralCollegeMakerByYear.py" -o -y "1976" && inkscape --without-gui "ElectoralCollege1976.svg" --export-png="ElectoralCollege1976.png"
python "./ElectoralCollegeMakerByYear.py" -o -y "1980" && inkscape --without-gui "ElectoralCollege1980.svg" --export-png="ElectoralCollege1980.png"
python "./ElectoralCollegeMakerByYear.py" -o -y "1984" && inkscape --without-gui "ElectoralCollege1984.svg" --export-png="ElectoralCollege1984.png"
python "./ElectoralCollegeMakerByYear.py" -o -y "1988" && inkscape --without-gui "ElectoralCollege1988.svg" --export-png="ElectoralCollege1988.png"
python "./ElectoralCollegeMakerByYear.py" -o -y "1992" && inkscape --without-gui "ElectoralCollege1992.svg" --export-png="ElectoralCollege1992.png"
python "./ElectoralCollegeMakerByYear.py" -o -y "1996" && inkscape --without-gui "ElectoralCollege1996.svg" --export-png="ElectoralCollege1996.png"
python "./ElectoralCollegeMakerByYear.py" -o -y "2000" && inkscape --without-gui "ElectoralCollege2000.svg" --export-png="ElectoralCollege2000.png"
python "./ElectoralCollegeMakerByYear.py" -o -y "2004" && inkscape --without-gui "ElectoralCollege2004.svg" --export-png="ElectoralCollege2004.png"
python "./ElectoralCollegeMakerByYear.py" -o -y "2008" && inkscape --without-gui "ElectoralCollege2008.svg" --export-png="ElectoralCollege2008.png"
python "./ElectoralCollegeMakerByYear.py" -o -y "2012" && inkscape --without-gui "ElectoralCollege2012.svg" --export-png="ElectoralCollege2012.png"
python "./ElectoralCollegeMakerByYear.py" -o -y "2016" && inkscape --without-gui "ElectoralCollege2016.svg" --export-png="ElectoralCollege2016.png"
